title: Anuradha Kumari
headline: test headline
description: >
  Tech Enthusiast | Web Developer | Learner | Trainer | Blogger | Speaker
theme: jekyll-theme-cayman
plugins:
  - jemoji
twitter_url: https://twitter.com/miracle_404
linkedin_url:	https://www.linkedin.com/in/anuradha15/
stackoverflow_url: https://stackoverflow.com/users/11406789/anuradha-kumari
hackerrank_url: https://www.hackerrank.com/anuradhak79
numOfBlogs: 12
prevTalks: 7
upcomingTalks: 2
google_analytics: UA-173916846-1
